// Mocks generated by Mockito 5.4.6 from annotations
// in biometric_auth/test/integration/biometric_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i8;

import 'package:biometric_auth/models/admin_settings.dart' as _i4;
import 'package:biometric_auth/models/user.dart' as _i2;
import 'package:biometric_auth/services/admin_settings_service.dart' as _i9;
import 'package:biometric_auth/services/auth_service.dart' as _i5;
import 'package:biometric_auth/services/ear_validator_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEarDetectionResult_1 extends _i1.SmartFake
    implements _i3.EarDetectionResult {
  _FakeEarDetectionResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdminSettings_2 extends _i1.SmartFake implements _i4.AdminSettings {
  _FakeAdminSettings_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i5.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> register({
    required String? nombres,
    required String? apellidos,
    required String? email,
    required String? identificadorUnico,
    required String? contrasena,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #nombres: nombres,
              #apellidos: apellidos,
              #email: email,
              #identificadorUnico: identificadorUnico,
              #contrasena: contrasena,
            }),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#register, [], {
                  #nombres: nombres,
                  #apellidos: apellidos,
                  #email: email,
                  #identificadorUnico: identificadorUnico,
                  #contrasena: contrasena,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> login({
    required String? identificadorUnico,
    required String? contrasena,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #identificadorUnico: identificadorUnico,
              #contrasena: contrasena,
            }),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#login, [], {
                  #identificadorUnico: identificadorUnico,
                  #contrasena: contrasena,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i2.User> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i6.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#getCurrentUser, [])),
            ),
          )
          as _i6.Future<_i2.User>);

  @override
  _i6.Future<void> registerEarPhoto(
    String? identificadorUnico,
    List<int>? photoBytes,
    int? photoNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerEarPhoto, [
              identificadorUnico,
              photoBytes,
              photoNumber,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> registerVoiceAudio(
    String? identificadorUnico,
    List<int>? audioBytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerVoiceAudio, [
              identificadorUnico,
              audioBytes,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> authenticateWithEarPhoto(
    String? identificadorUnico,
    List<int>? photoBytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#authenticateWithEarPhoto, [
              identificadorUnico,
              photoBytes,
            ]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> authenticateWithVoice(
    String? identificadorUnico,
    List<int>? audioBytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#authenticateWithVoice, [
              identificadorUnico,
              audioBytes,
            ]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);
}

/// A class which mocks [EarValidatorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEarValidatorService extends _i1.Mock
    implements _i3.EarValidatorService {
  MockEarValidatorService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.EarDetectionResult> validateEar(_i8.Uint8List? imageBytes) =>
      (super.noSuchMethod(
            Invocation.method(#validateEar, [imageBytes]),
            returnValue: _i6.Future<_i3.EarDetectionResult>.value(
              _FakeEarDetectionResult_1(
                this,
                Invocation.method(#validateEar, [imageBytes]),
              ),
            ),
          )
          as _i6.Future<_i3.EarDetectionResult>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AdminSettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminSettingsService extends _i1.Mock
    implements _i9.AdminSettingsService {
  MockAdminSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool authenticate(String? password, String? secretKey) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [password, secretKey]),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Future<_i4.AdminSettings> loadSettings() =>
      (super.noSuchMethod(
            Invocation.method(#loadSettings, []),
            returnValue: _i6.Future<_i4.AdminSettings>.value(
              _FakeAdminSettings_2(this, Invocation.method(#loadSettings, [])),
            ),
          )
          as _i6.Future<_i4.AdminSettings>);

  @override
  _i6.Future<void> saveSettings(_i4.AdminSettings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#saveSettings, [settings]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> resetToDefaults() =>
      (super.noSuchMethod(
            Invocation.method(#resetToDefaults, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> toggleTheme() =>
      (super.noSuchMethod(
            Invocation.method(#toggleTheme, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateApiUrl(String? newUrl) =>
      (super.noSuchMethod(
            Invocation.method(#updateApiUrl, [newUrl]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateSyncInterval(int? minutes) =>
      (super.noSuchMethod(
            Invocation.method(#updateSyncInterval, [minutes]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> exportSettings() =>
      (super.noSuchMethod(
            Invocation.method(#exportSettings, []),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#exportSettings, []),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<void> importSettings(String? jsonString) =>
      (super.noSuchMethod(
            Invocation.method(#importSettings, [jsonString]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  String generatePasswordHash(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#generatePasswordHash, [password]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#generatePasswordHash, [password]),
            ),
          )
          as String);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );
}
